// Décrit, pour chaque collection Appwrite, les champs à afficher dans le
// back-office générique (liste + formulaire de création/édition).
// "key" doit correspondre à une entrée de src/lib/appwrite.js (COLLECTIONS)
// et de src/data/seed/*.json.

const BRANCH_COLOR_OPTIONS = [
  { value: "amber", label: "Ambre (BTP)" },
  { value: "brick", label: "Brique (Immobilier)" },
  { value: "teal", label: "Sarcelle (Aquaculture)" },
  { value: "indigo", label: "Indigo (Opentek)" },
  { value: "slate", label: "Ardoise (Commerce)" },
];

export const ADMIN_COLLECTIONS = [
  {
    key: "branches",
    label: "Filières / Branches",
    titleField: "name_fr",
    fields: [
      { name: "code", label: "Code", type: "text" },
      { name: "color", label: "Couleur", type: "select", options: BRANCH_COLOR_OPTIONS },
      { name: "name_fr", label: "Nom (FR)", type: "text" },
      { name: "name_en", label: "Nom (EN)", type: "text" },
      { name: "title_fr", label: "Titre (FR)", type: "text" },
      { name: "title_en", label: "Titre (EN)", type: "text" },
      { name: "description_fr", label: "Description (FR)", type: "textarea" },
      { name: "description_en", label: "Description (EN)", type: "textarea" },
    ],
  },
  {
    key: "values",
    label: "Valeurs",
    titleField: "title_fr",
    fields: [
      { name: "order", label: "Ordre", type: "number" },
      { name: "title_fr", label: "Titre (FR)", type: "text" },
      { name: "title_en", label: "Titre (EN)", type: "text" },
      { name: "description_fr", label: "Description (FR)", type: "textarea" },
      { name: "description_en", label: "Description (EN)", type: "textarea" },
    ],
  },
  {
    key: "services",
    label: "Services",
    titleField: "title_fr",
    fields: [
      { name: "branch", label: "Filière", type: "relation", relatedCollection: "branches", labelField: "title_fr" },
      { name: "title_fr", label: "Titre (FR)", type: "text" },
      { name: "title_en", label: "Titre (EN)", type: "text" },
      { name: "description_fr", label: "Description (FR)", type: "textarea" },
      { name: "description_en", label: "Description (EN)", type: "textarea" },
    ],
  },
  {
    key: "projects",
    label: "Réalisations",
    titleField: "title_fr",
    fields: [
      { name: "branch", label: "Filière", type: "relation", relatedCollection: "branches", labelField: "title_fr" },
      { name: "title_fr", label: "Titre (FR)", type: "text" },
      { name: "title_en", label: "Titre (EN)", type: "text" },
      { name: "location_fr", label: "Lieu (FR)", type: "text" },
      { name: "location_en", label: "Lieu (EN)", type: "text" },
      { name: "description_fr", label: "Description (FR)", type: "textarea" },
      { name: "description_en", label: "Description (EN)", type: "textarea" },
      { name: "image", label: "URL image", type: "text" },
    ],
  },
  {
    key: "team",
    label: "Équipe",
    titleField: "name",
    fields: [
      { name: "name", label: "Nom complet", type: "text" },
      { name: "role_fr", label: "Poste (FR)", type: "text" },
      { name: "role_en", label: "Poste (EN)", type: "text" },
      { name: "bio_fr", label: "Biographie (FR)", type: "textarea" },
      { name: "bio_en", label: "Biographie (EN)", type: "textarea" },
      { name: "photo", label: "URL photo", type: "text" },
    ],
  },
  {
    key: "testimonials",
    label: "Témoignages",
    titleField: "name",
    fields: [
      { name: "name", label: "Nom du client", type: "text" },
      { name: "role_fr", label: "Fonction / société (FR)", type: "text" },
      { name: "role_en", label: "Fonction / société (EN)", type: "text" },
      { name: "quote_fr", label: "Témoignage (FR)", type: "textarea" },
      { name: "quote_en", label: "Témoignage (EN)", type: "textarea" },
    ],
  },
  {
    key: "jobs",
    label: "Offres d'emploi",
    titleField: "title_fr",
    fields: [
      { name: "title_fr", label: "Intitulé (FR)", type: "text" },
      { name: "title_en", label: "Intitulé (EN)", type: "text" },
      { name: "branch", label: "Filière", type: "relation", relatedCollection: "branches", labelField: "title_fr" },
      { name: "type_fr", label: "Type de contrat (FR)", type: "text" },
      { name: "type_en", label: "Type de contrat (EN)", type: "text" },
      { name: "location_fr", label: "Lieu (FR)", type: "text" },
      { name: "location_en", label: "Lieu (EN)", type: "text" },
      { name: "description_fr", label: "Description (FR)", type: "textarea" },
      { name: "description_en", label: "Description (EN)", type: "textarea" },
    ],
  },
  {
    key: "events",
    label: "Événements",
    titleField: "title_fr",
    fields: [
      { name: "title_fr", label: "Titre (FR)", type: "text" },
      { name: "title_en", label: "Titre (EN)", type: "text" },
      { name: "date", label: "Date", type: "date" },
      { name: "location_fr", label: "Lieu (FR)", type: "text" },
      { name: "location_en", label: "Lieu (EN)", type: "text" },
      { name: "description_fr", label: "Description (FR)", type: "textarea" },
      { name: "description_en", label: "Description (EN)", type: "textarea" },
    ],
  },
  {
    key: "blog",
    label: "Articles de blog",
    titleField: "title_fr",
    fields: [
      { name: "title_fr", label: "Titre (FR)", type: "text" },
      { name: "title_en", label: "Titre (EN)", type: "text" },
      { name: "date", label: "Date", type: "date" },
      { name: "author", label: "Auteur", type: "text" },
      { name: "excerpt_fr", label: "Résumé (FR)", type: "textarea" },
      { name: "excerpt_en", label: "Résumé (EN)", type: "textarea" },
      { name: "content_fr", label: "Contenu complet (FR)", type: "textarea" },
      { name: "content_en", label: "Contenu complet (EN)", type: "textarea" },
      { name: "coverImage", label: "Image de couverture (URL)", type: "text" },
    ],
  },
  {
    key: "rentals", label: "Maisons à louer",
    titleField: "title_fr",
    fields: [
      { name: "title_fr", label: "Titre (FR)", type: "text" },
      { name: "title_en", label: "Titre (EN)", type: "text" },
      { name: "location_fr", label: "Lieu (FR)", type: "text" },
      { name: "location_en", label: "Lieu (EN)", type: "text" },
      { name: "rooms", label: "Nombre de pièces", type: "number" },
      { name: "price_fr", label: "Loyer (FR)", type: "text" },
      { name: "price_en", label: "Loyer (EN)", type: "text" },
      { name: "description_fr", label: "Description (FR)", type: "textarea" },
      { name: "description_en", label: "Description (EN)", type: "textarea" },
      { name: "images", label: "Photos", type: "imagelist" },
    ],
  },
  {
    key: "lands", label: "Terrains à vendre",
    titleField: "title_fr",
    fields: [
      { name: "title_fr", label: "Titre (FR)", type: "text" },
      { name: "title_en", label: "Titre (EN)", type: "text" },
      { name: "location_fr", label: "Lieu (FR)", type: "text" },
      { name: "location_en", label: "Lieu (EN)", type: "text" },
      { name: "surface", label: "Surface (ex : 500 m²)", type: "text" },
      { name: "price_fr", label: "Prix (FR)", type: "text" },
      { name: "price_en", label: "Prix (EN)", type: "text" },
      { name: "description_fr", label: "Description (FR)", type: "textarea" },
      { name: "description_en", label: "Description (EN)", type: "textarea" },
      { name: "images", label: "Photos", type: "imagelist" },
    ],
  },
  {
    key: "commerce", label: "Commerce général",
    titleField: "title_fr",
    fields: [
      { name: "title_fr", label: "Titre (FR)", type: "text" },
      { name: "title_en", label: "Titre (EN)", type: "text" },
      { name: "description_fr", label: "Description (FR)", type: "textarea" },
      { name: "description_en", label: "Description (EN)", type: "textarea" },
      { name: "images", label: "Photos (max 3 conseillées)", type: "imagelist" },
    ],
  },
  {
    key: "newsletter", label: "Abonnés newsletter",
    titleField: "email",
    readOnly: true,
    fields: [
      { name: "email", label: "Email", type: "text" },
      { name: "date", label: "Date d'inscription", type: "text" },
    ],
  },
  {
    key: "messages", label: "Messages reçus",
    titleField: "email",
    readOnly: true,
    fields: [
      { name: "name", label: "Nom", type: "text" },
      { name: "email", label: "Email", type: "text" },
      { name: "message", label: "Message", type: "textarea" },
      { name: "date", label: "Date", type: "text" },
    ],
  },
  {
    key: "settings", label: "Coordonnées & réseaux sociaux",
    titleField: "contactEmail",
    singleton: true,
    fields: [
      { name: "contactEmail", label: "Email de contact", type: "text" },
      { name: "contactPhone", label: "Téléphone de contact", type: "text" },
      { name: "address", label: "Adresse", type: "text" },
      { name: "facebookUrl", label: "URL Facebook", type: "text" },
      { name: "linkedinUrl", label: "URL LinkedIn", type: "text" },
      { name: "twitterUrl", label: "URL X / Twitter", type: "text" },
    ],
  },
];
